---
resources:
  - ../users/kubernetes
  - ../authentication/kubernetes
  - ../trainings/kubernetes
  - ../goals/kubernetes
patchesStrategicMerge:
  - set_goals_config.yaml
  - set_trainings_config.yaml
  - set_users_config.yaml
# See "Set firebase credentials in README.md"
#  - set_trainings_firebase_credential.yaml
# Uncomment patches below to use local images.
#patchesJson6902:
#  - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: auth
#   path: set_auth_deployment.yaml
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: users
#   path: set_users_deployment.yaml
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: trainings
#   path: set_trainings_deployment.yaml
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: goals
#   path: set_goals_deployment.yaml
