---
resources:
  - ../users/kubernetes
  - ../authentication/kubernetes
  - ../trainings/kubernetes
patchesStrategicMerge:
  - set_trainings_config.yaml
  - set_users_config.yaml
# Uncomment patches below to use local images.
#patchesJson6902:
#  - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: auth
#   path: set_auth_deployment.yaml
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: users
#   path: set_users_deployment.yaml
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: trainings
#   path: set_trainings_deployment.yaml
