---
resources:
  - ../users/kubernetes
  - ../authentication/kubernetes
patchesStrategicMerge:
  - set_users_config.yaml
#patchesJson6902:
#  - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: auth
#   path: set_auth_deployment.yaml
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: users
#   path: set_users_deployment.yaml